# Generated by Django 3.1.2 on 2020-11-02 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderimodel',
            name='resim',
            field=models.ImageField(default='0', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='olus_zaman',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Zamanı'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='yayim_zaman',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yayımlanma Zamanı'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='yazi',
            field=models.TextField(verbose_name='Blog Metni'),
        ),
    ]
