# Generated by Django 3.1.2 on 2020-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisimmodel',
            name='soyadi',
            field=models.CharField(max_length=70),
        ),
    ]
